### ISSUE TITLE
是不是 Typecho v1.2 不能使用？

### ISSUE THREAD

**Issue by bear5210** [mulingyuer/Typecho_Theme_JJ#24]
我使用时报错了：
Typecho\Widget::__construct(): Argument #1 ($request) must be of type Typecho\Widget\Request, Typecho\Request given, called in /var/www/typecho/usr/themes/Typecho_Theme_JJ/functions.php on line 238

**Comment by mulingyuer** [comment]
1.2才出啊，而且大改了，很多语法不一样了，目前主题只能1.1

**Comment by mulingyuer** [comment]
1.2版本适配有时间就写，1.1稳定无问题
