### ISSUE TITLE
修改不了logo

### ISSUE THREAD

**Issue by Jinhk084** [mulingyuer/Typecho_Theme_JJ#34]
将/static/images/favicon/ 路径里面的图片替换无法修改 , 甚至将images文件夹删除 , 也不影响网站原本logo 的加载 , 请问怎么解决

**Comment by mulingyuer** [comment]
看文档了吗？你说的favicon是站点图标，是给浏览器使用的，如果要更换header顶栏的图标，那就是另一个位置，我都在文档说明了，可以看下，然后也有可能是浏览器缓存导致的，你可以ctrl+shift+r清理缓存刷新看看

**Comment by Jinhk084** [comment]
嗯嗯 , 解决了 , 是因为没有清缓存的原因 , 谢谢 , 主题真的很棒!

**Comment by mulingyuer** [comment]
> 嗯嗯 , 解决了 , 是因为没有清缓存的原因 , 谢谢 , 主题真的很棒!

毕竟自用主题，走的好用简单方☺️
