### ISSUE TITLE
登陆界面右边的二维码是什么来着？

### ISSUE THREAD

**Issue by zsdili** [mulingyuer/Typecho_Theme_JJ#37]
感谢分享这个主题，不过，扫码后打开的是黄色网站，要在哪里去掉？

**Comment by mulingyuer** [comment]
你肯定是用微信啥扫描的（国内辣鸡封闭环境），你可以用qq扫试试，我用qq扫是直接打开的，只是公共图床的一个图片直链而已，并不是你认为的那种。
