### ISSUE TITLE
建议：默认头像能不能换成名字首写字母or汉字或者用qq头像，磨人的太丑了

### ISSUE THREAD

**Issue by shuaiplus** [mulingyuer/Typecho_Theme_JJ#39]
![image](https://user-images.githubusercontent.com/100134295/236776644-7fab1b9f-0bfb-4146-b223-aa9f3773ffc4.png)
或者教我怎么换也行(￣3￣)

**Comment by shuaiplus** [comment]
解决了，用了个插件就可以了，我改了一下头像源，可以直接拿来用，可以获取qq头像，可以设置默认头像风格（每个人都不一样）。插件：https://github.com/shuaiplus/GravatarServer

**Comment by mulingyuer** [comment]
会不会有暴露对方qq号的风险

**Comment by shuaiplus** [comment]
![image](https://user-images.githubusercontent.com/100134295/236798996-0cc6568e-6581-411b-856b-05117daeee5b.png)
我觉得不会暴露把

**Comment by mulingyuer** [comment]
加密了，那可以，这个插件我回头丢使用文档里去

**Comment by shuaiplus** [comment]
![image](https://user-images.githubusercontent.com/100134295/236799475-69d03f7a-cbc1-4171-9507-073676021c73.png)
我的小恐龙为啥不跑了？挂了代理也不跑

**Comment by mulingyuer** [comment]
按空格呀，你网站发来我看看

**Comment by shuaiplus** [comment]
> 按空格呀，你网站发来我看看

没认真看提示，my bad

**Comment by mulingyuer** [comment]
我找泽泽了解了下最新的做法，目前新用法已更新到使用文档了，你可以查看头像换源那篇了解一下，比你这个插件省事多了

**Comment by shuaiplus** [comment]
牛啊，其实我想找的就是这种，接口里自带qq头像的，辛苦了
