### ISSUE TITLE
需要加载插件的footer方法

### ISSUE THREAD

**Issue by wuqiyin** [mulingyuer/Typecho_Theme_JJ#48]
![image](https://github.com/mulingyuer/Typecho_Theme_JJ/assets/26370779/d3d40f44-cf81-4ec7-b27e-3a07dc334ae2)
如果不加这个代码的话，这个插件就无法用了：https://github.com/mrgeneralgoo/typecho-markdown

**Comment by mulingyuer** [comment]
好的，本周末会更新修复版本

**Comment by mulingyuer** [comment]
v2.2.4 版本已修复
