### ISSUE TITLE
网站里的链接不带端口号

### ISSUE THREAD

**Issue by cui8** [mulingyuer/Typecho_Theme_JJ#53]
家宽，使用域名（这个域名解析到的是IPv6地址）。
域名【xxxx.xyz:8888】可以访问，但是点击文章的时候，跳转链接不带端口号了，只有【xxxx.xyz】，这个问题怎么解决，让网站里的每个链接都带端口号。
希望大佬帮帮孩子吧

**Comment by mulingyuer** [comment]
你应该在typecho的设置里把访问地址改成你的域名，如果你要带端口，设置的时候就带上端口吧。

**Comment by mulingyuer** [comment]
那我就不知道了，理论上讲通过域名访问是不需要带端口的，有可能是域名解析和nginx配置之类的没设置对，建议谷歌搜索看看有没有类似的案例吧

**Comment by cui8** [comment]
> 那我就不知道了，理论上讲通过域名访问是不需要带端口的，有可能是域名解析和nginx配置之类的没设置对，建议谷歌搜索看看有没有类似的案例吧

![image](https://github.com/mulingyuer/Typecho_Theme_JJ/assets/70044239/2bb2d89b-2eb7-4c64-806f-03846877a125)


![image](https://github.com/mulingyuer/Typecho_Theme_JJ/assets/70044239/0e3dcb9a-e21c-425a-8f12-57c865f1d9c9)

**Comment by cui8** [comment]
> 那我就不知道了，理论上讲通过域名访问是不需要带端口的，有可能是域名解析和nginx配置之类的没设置对，建议谷歌搜索看看有没有类似的案例吧

大佬知道怎么让它里面的链接带端口吗？折腾一天了，还不行，官方默认模板也不行

**Comment by mulingyuer** [comment]
母鸡，我都是vps建站，没整过家庭网映射域名访问这些

**Comment by cui8** [comment]
> 母鸡，我都是vps建站，没整过家庭网映射域名访问这些

谢谢大佬，看来只能内网访问了

**Comment by cui8** [comment]
已解决
