### ISSUE TITLE
17.10.30版本下编辑主题报错

### ISSUE THREAD

**Issue by Junehck** [mulingyuer/Typecho_Theme_JJ#55]
typecho:17.10.30
php:5.6Fatal error: Class 'Typecho\Widget\Helper\Form\Element\Textarea' not found in
编辑主题提示
![image](https://github.com/mulingyuer/Typecho_Theme_JJ/assets/103053746/7a8d5c37-1939-4b5b-a803-f67311e62287)

**Comment by Junehck** [comment]
解决了

**Comment by Junehck** [comment]
看了文档发现是版本太低了

**Comment by mulingyuer** [comment]
> 看了文档发现是版本太低了
> 

用Typecho 1.2版本
