### ISSUE TITLE
github 主题下

### ISSUE THREAD

**Issue by wuqiyin** [mulingyuer/Typecho_Theme_JJ#57]
![image](https://github.com/mulingyuer/Typecho_Theme_JJ/assets/26370779/51522c65-50bb-40a0-adb9-b54478249ad5)

**Comment by mulingyuer** [comment]
ok，这周末安排修复一下

**Comment by mulingyuer** [comment]
v2.2.9版本已修复，直接和掘金新增的代码头一样了
