### ISSUE TITLE
首页最新tab点击无效

### ISSUE THREAD

**Issue by wuqiyin** [mulingyuer/Typecho_Theme_JJ#61]
![image](https://github.com/mulingyuer/Typecho_Theme_JJ/assets/26370779/dff6d62b-b2b8-479d-8589-9a13a035f797)

**Comment by mulingyuer** [comment]
是的，因为typecho没有提供对应的api，php我也不是很会，等大佬提供帮助呢

**Comment by wuqiyin** [comment]
移动端能否加个目录功能



***@***.***
 
发件人： 木灵鱼儿
发送时间： 2023-10-05 22:46
收件人： mulingyuer/Typecho_Theme_JJ
抄送： silverwq; Author
主题： Re: [mulingyuer/Typecho_Theme_JJ] 首页最新tab点击无效 (Issue #61)
是的，因为typecho没有提供对应的api，php我也不是很会，等大佬提供帮助呢

**Comment by mulingyuer** [comment]
啥目录功能，移动端点击对应分类就能进入到分类列表页啊，点击展开就行了，事实上移动端很少有人去看分类的，大部分浏览量其实都是pc

**Comment by wuqiyin** [comment]
文章的目录哈，不是分类



***@***.***
 
发件人： 木灵鱼儿
发送时间： 2023-10-05 23:08
收件人： mulingyuer/Typecho_Theme_JJ
抄送： silverwq; Author
主题： Re: [mulingyuer/Typecho_Theme_JJ] 首页最新tab点击无效 (Issue #61)
啥目录功能，移动端点击对应分类就能进入到分类列表页啊，点击展开就行了，事实上移动端很少有人去看分类的，大部分浏览量其实都是pc

**Comment by mulingyuer** [comment]
目录树啊，我也在想，但是找不到合适的展示方式

**Comment by mulingyuer** [comment]
已经新增移动端的目录树了，但是在scroll状态下下拉关闭有点卡顿，暂时没找到合适的解决方案，但是已经很不错了，可以体验。
