### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by jianhuangXie** [mulingyuer/Typecho_Theme_JJ#64]
目前只有qq扫一扫登录；现在提示被禁止了
可以添加个github登录或者邮箱注册码？

**Comment by mulingyuer** [comment]
啊，你来真的啊？

**Comment by jianhuangXie** [comment]
哈哈；没注意到是typecho，不过界面是仿的真心好
也有登录插件，只是加了没意义。
要不要考虑移植到wordpress？

**Comment by mulingyuer** [comment]
wp太卡了，受不了
