### ISSUE TITLE
可以商用吗？

### ISSUE THREAD

**Issue by dh360** [mulingyuer/Typecho_Theme_JJ#67]
看到本项目采用的开源协议，我觉得没问题，
但是看到“拿我的主题去卖， 被告”啥的，有些不理解。 
可以做一个论坛商用吗， 自己公司运营的那种

**Comment by mulingyuer** [comment]
不太清楚耶，ui是仿掘金的，你商用不知道会不会有问题。

**Comment by dh360** [comment]
> 不太清楚耶，ui是仿掘金的，你可能不知道会不会有问题。
明白了， ui类似应该没事儿吧, 知乎，掘金 板式好像差不离
