### ISSUE TITLE
很奇怪的问题

### ISSUE THREAD

**Issue by FREE-U** [mulingyuer/Typecho_Theme_JJ#76]
在最新一版的主题中出现了一个问题
![Screenshot_2024_0405_192301](https://github.com/mulingyuer/Typecho_Theme_JJ/assets/122505014/30d2080d-987a-4532-981c-a01a89a967ba)
非常明显有些东西不显示了
然后进入一个文章
![Screenshot_2024_0405_192318](https://github.com/mulingyuer/Typecho_Theme_JJ/assets/122505014/9549c48d-f38b-42b7-a311-ba03003ed756)
则恢复
![Screenshot_2024_0405_192327](https://github.com/mulingyuer/Typecho_Theme_JJ/assets/122505014/b8ae84c6-ab93-4e12-96c8-fd1e8bff46ec)

**Comment by FREE-U** [comment]
这并不是一个偶然性问题，我试过更换设备和浏览器，但是第一次加载还是不能全部显示出来，必须要进入文章然后再回到主页才能正常显示

**Comment by mulingyuer** [comment]
这是在加载字体图标
