### ISSUE TITLE
文章内插入网易云音乐组件会变白

### ISSUE THREAD

**Issue by FREE-U** [mulingyuer/Typecho_Theme_JJ#77]
![Screenshot_2024_0406_174252](https://github.com/mulingyuer/Typecho_Theme_JJ/assets/122505014/f7491b55-7639-481b-af44-70cd5ceda0b8)
这是一个网易云那个音乐组件<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=340 height=86 src="//music.163.com/outchain/player?type=2&id=1377530437&auto=1&height=66"></iframe>插入会让移动端那里变白，PC端还算正常？

**Comment by mulingyuer** [comment]
iframe 目前只做了视频插入适配，所以高度是固定的，你是指的宽度溢出问题还是？有具体链接吗，我看看怎么回事

**Comment by mulingyuer** [comment]
v2.3.3 已增加ifrmae支持，具体可以查看文档中的 **文章小技巧**
