### ISSUE TITLE
编辑器插入图片，便捷功能

### ISSUE THREAD

**Issue by zimokj** [mulingyuer/Typecho_Theme_JJ#82]
大佬什么时候有空在编辑器加入插入图片功能啊，点击附件图片，自动在原文，插入makdown格式和附件图片链接，像自带编辑器那样

比如上传附件图片—>点击附件图片—>弹窗，可以更改附件的图片地址，和描述（默认为附件地址和默认图片名称），点击确定——>自动插入原文

![Alt文本](图片链接地址)

**Comment by mulingyuer** [comment]
搞不定，typecho官方把文件列表的点击事件给阻止冒泡了，我没法通过js手段去取得插入的内容，等以后看看有无解决办法吧！

**Comment by mulingyuer** [comment]
插件v1.2.2版本加入了，注意看更新日志
