### ISSUE TITLE
更便捷的修改主题相关配置建议

### ISSUE THREAD

**Issue by alexxin139** [mulingyuer/Typecho_Theme_JJ#88]
希望能在Typecho控制台中直接修改fanvion图标和heard图标等配置

**Comment by mulingyuer** [comment]
> 希望能在Typecho控制台中直接修改fanvion图标和heard图标等配置

有点麻烦，因为一个站点图标为了兼容不同的客户端是有很多规格的，你可以用文档中提供的一键生成文件的网站快速生成，替换本地资源即可。

**Comment by mulingyuer** [comment]
实在不行你可以直接修改主题目录下 Typecho_Theme_JJ/php_modules/default_head.php 这个问题，里面是对应的站点图标，你可以自己魔改
