### ISSUE TITLE
一个幻灯片

### ISSUE THREAD

**Issue by FREE-U** [mulingyuer/Typecho_Theme_JJ#98]
![Screenshot_2024_0807_200946](https://github.com/user-attachments/assets/9c9cc7c4-7641-4b30-907e-394cae0170d7)
可以做个幻灯片不😙

**Comment by mulingyuer** [comment]
??? 啥幻灯片

**Comment by FREE-U** [comment]
![IMG_20240807_201934](https://github.com/user-attachments/assets/dddc60cb-148a-4f14-92d9-58758366e854)
这东西不都叫幻灯片吗

**Comment by mulingyuer** [comment]
这个是轮播啊，掘金没有这个东西，不过你可以自己加啊，好多教程的。
